apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "streamplatform.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "streamplatform.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /api/nlp
    route:
    - destination:
        host: nlp-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /api/vjepa
    route:
    - destination:
        host: vjepa-service
        port:
          number: 80
  - route:
    - destination:
        host: {{ include "streamplatform.fullname" . }}
        port:
          number: {{ .Values.service.port }}
